//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErogeDiary.Controls.Properties {
    using System;
    
    
    /// <summary>
    /// ローカライズされた文字列などを検索するための厳密に型指定されたリソース クラス。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        /// このクラスで使用された、被キャッシュ ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErogeDiary.Controls.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// すべてのスレッドの CurrentUICulture プロパティをオーバーライドします
        /// この厳密に型指定されたリソース クラスを使用したリソースの検索。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// 金 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string CalendarHeatmap_Friday {
            get {
                return ResourceManager.GetString("CalendarHeatmap_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        /// 月 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string CalendarHeatmap_Monday {
            get {
                return ResourceManager.GetString("CalendarHeatmap_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        /// {0}月 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string CalendarHeatmap_MonthFormat {
            get {
                return ResourceManager.GetString("CalendarHeatmap_MonthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// 土 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string CalendarHeatmap_Saturday {
            get {
                return ResourceManager.GetString("CalendarHeatmap_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        /// 日 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string CalendarHeatmap_Sunday {
            get {
                return ResourceManager.GetString("CalendarHeatmap_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        /// 木 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string CalendarHeatmap_Thursday {
            get {
                return ResourceManager.GetString("CalendarHeatmap_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        /// 火 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string CalendarHeatmap_Tuesday {
            get {
                return ResourceManager.GetString("CalendarHeatmap_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        /// 水 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string CalendarHeatmap_Wednesday {
            get {
                return ResourceManager.GetString("CalendarHeatmap_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        /// {0}回 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Histogram_CountTooltipFormat {
            get {
                return ResourceManager.GetString("Histogram_CountTooltipFormat", resourceCulture);
            }
        }
    }
}
