//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErogeDiary.Properties {
    using System;
    
    
    /// <summary>
    /// ローカライズされた文字列などを検索するための厳密に型指定されたリソース クラス。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        /// このクラスで使用された、被キャッシュ ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErogeDiary.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// すべてのスレッドの CurrentUICulture プロパティをオーバーライドします
        /// この厳密に型指定されたリソース クラスを使用したリソースの検索。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// 予期しないエラーが発生しました。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string App_UnexpectedError {
            get {
                return ResourceManager.GetString("App_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        /// 追加 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        /// 参照 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Browse {
            get {
                return ResourceManager.GetString("Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        /// キャンセル のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// 完了 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Complete {
            get {
                return ResourceManager.GetString("Common_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        /// 削除 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        /// OK のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        /// 更新 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Update {
            get {
                return ResourceManager.GetString("Common_Update", resourceCulture);
            }
        }
        
        /// <summary>
        /// yyyy年MM月dd日 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string DateFormat_Long {
            get {
                return ResourceManager.GetString("DateFormat_Long", resourceCulture);
            }
        }
        
        /// <summary>
        /// 確認 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_ConfirmTitle {
            get {
                return ResourceManager.GetString("Dialog_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// エラー のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_ErrorTitle {
            get {
                return ResourceManager.GetString("Dialog_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// 情報 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_InfoTitle {
            get {
                return ResourceManager.GetString("Dialog_InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// 実行ファイル(*.exe)|*.exe のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string FileFilter_Executable {
            get {
                return ResourceManager.GetString("FileFilter_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        /// 画像ファイル(*.png;*.jpg;*.jpeg;*.bmp)|*.png;*.jpg;*.jpeg;*.bmp のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string FileFilter_Image {
            get {
                return ResourceManager.GetString("FileFilter_Image", resourceCulture);
            }
        }
        
        /// <summary>
        /// ゲームを起動 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Game_ActionStart {
            get {
                return ResourceManager.GetString("Game_ActionStart", resourceCulture);
            }
        }
        
        /// <summary>
        /// ゲームの登録を解除 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Game_DeleteRegistration {
            get {
                return ResourceManager.GetString("Game_DeleteRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        /// ゲームの登録を解除しますか？
        ///セーブデータやゲーム本体は削除されません。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Game_DeleteRegistrationConfirmation {
            get {
                return ResourceManager.GetString("Game_DeleteRegistrationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        /// 解除に成功しました。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Game_DeleteRegistrationSucceeded {
            get {
                return ResourceManager.GetString("Game_DeleteRegistrationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        /// DMM GAME PLAYER でインストールされたゲームはここから起動できません。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Game_DmmLaunchUnavailable {
            get {
                return ResourceManager.GetString("Game_DmmLaunchUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        /// 編集 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Game_Edit {
            get {
                return ResourceManager.GetString("Game_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        /// 実行ファイルのパスが設定されていません。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Game_ExecutablePathMissing {
            get {
                return ResourceManager.GetString("Game_ExecutablePathMissing", resourceCulture);
            }
        }
        
        /// <summary>
        /// ゲームの情報が見つからないため解除できませんでした。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Game_InfoMissingForDelete {
            get {
                return ResourceManager.GetString("Game_InfoMissingForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        /// 未プレイ のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Game_NotPlayed {
            get {
                return ResourceManager.GetString("Game_NotPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        /// ゲームの起動に失敗しました。
        ///{0} のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Game_StartFailedFormat {
            get {
                return ResourceManager.GetString("Game_StartFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// ゲームの編集 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameEdit_Title {
            get {
                return ResourceManager.GetString("GameEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// ブランド のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameField_Brand {
            get {
                return ResourceManager.GetString("GameField_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        /// 攻略済み のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameField_Cleared {
            get {
                return ResourceManager.GetString("GameField_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        /// 攻略日 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameField_ClearedAt {
            get {
                return ResourceManager.GetString("GameField_ClearedAt", resourceCulture);
            }
        }
        
        /// <summary>
        /// DMM GAME PLAYER でインストール のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameField_DmmInstalled {
            get {
                return ResourceManager.GetString("GameField_DmmInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        /// 批評空間のゲームURL のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameField_ErogameScapeUrl {
            get {
                return ResourceManager.GetString("GameField_ErogameScapeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        /// 実行ファイルの場所 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameField_ExecutableFilePath {
            get {
                return ResourceManager.GetString("GameField_ExecutableFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        /// サムネイル画像の場所（URLまたはファイルパス） のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameField_ImageLocation {
            get {
                return ResourceManager.GetString("GameField_ImageLocation", resourceCulture);
            }
        }
        
        /// <summary>
        /// 発売日 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameField_ReleaseDate {
            get {
                return ResourceManager.GetString("GameField_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// タイトル のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameField_Title {
            get {
                return ResourceManager.GetString("GameField_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// ゲームウィンドウに表示されるタイトル のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameField_WindowTitle {
            get {
                return ResourceManager.GetString("GameField_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// 批評空間から自動入力 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameRegistration_AutoFillFromErogameScape {
            get {
                return ResourceManager.GetString("GameRegistration_AutoFillFromErogameScape", resourceCulture);
            }
        }
        
        /// <summary>
        /// 既に同じゲームが登録されています。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameRegistration_DuplicateGame {
            get {
                return ResourceManager.GetString("GameRegistration_DuplicateGame", resourceCulture);
            }
        }
        
        /// <summary>
        /// 有効なURLではありません のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameRegistration_InvalidErogameScapeUrl {
            get {
                return ResourceManager.GetString("GameRegistration_InvalidErogameScapeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        /// 登録 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameRegistration_RegisterButton {
            get {
                return ResourceManager.GetString("GameRegistration_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// ゲームの登録 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameRegistration_Title {
            get {
                return ResourceManager.GetString("GameRegistration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// 例：https://erogamescape.dyndns.org/~ap2/ero/toukei_kaiseki/game.php?game=12345 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string GameRegistration_UrlExample {
            get {
                return ResourceManager.GetString("GameRegistration_UrlExample", resourceCulture);
            }
        }
        
        /// <summary>
        /// すべて のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Home_Filter_All {
            get {
                return ResourceManager.GetString("Home_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        /// 攻略済み のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Home_Filter_Cleared {
            get {
                return ResourceManager.GetString("Home_Filter_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        /// 未攻略 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Home_Filter_NotCleared {
            get {
                return ResourceManager.GetString("Home_Filter_NotCleared", resourceCulture);
            }
        }
        
        /// <summary>
        /// 絞り込み のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Home_FilterLabel {
            get {
                return ResourceManager.GetString("Home_FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// ブランド順 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Home_Order_ByBrand {
            get {
                return ResourceManager.GetString("Home_Order_ByBrand", resourceCulture);
            }
        }
        
        /// <summary>
        /// プレイ時間が長い順 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Home_Order_ByLongPlayTime {
            get {
                return ResourceManager.GetString("Home_Order_ByLongPlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        /// 最近登録した順 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Home_Order_ByNewRegistration {
            get {
                return ResourceManager.GetString("Home_Order_ByNewRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        /// 発売日が新しい順 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Home_Order_ByNewReleaseDate {
            get {
                return ResourceManager.GetString("Home_Order_ByNewReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// 最近プレイした順 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Home_Order_ByRecentPlay {
            get {
                return ResourceManager.GetString("Home_Order_ByRecentPlay", resourceCulture);
            }
        }
        
        /// <summary>
        /// 並び替え のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Home_OrderLabel {
            get {
                return ResourceManager.GetString("Home_OrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// ゲームを登録 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Home_RegisterGame {
            get {
                return ResourceManager.GetString("Home_RegisterGame", resourceCulture);
            }
        }

        /// <summary>
        /// ホーム のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Home
        {
            get
            {
                return ResourceManager.GetString("Main_Home", resourceCulture);
            }
        }

        /// <summary>
        /// 計測中 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Monitoring {
            get {
                return ResourceManager.GetString("Main_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        /// 設定 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        /// 合計プレイ時間 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_TotalPlayTime {
            get {
                return ResourceManager.GetString("Main_TotalPlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        /// ゲームの実行ファイルを選択してください のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFile_SelectExecutable {
            get {
                return ResourceManager.GetString("OpenFile_SelectExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        /// サムネイル画像を選択してください のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFile_SelectThumbnail {
            get {
                return ResourceManager.GetString("OpenFile_SelectThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        /// プレイ時間の平均値 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogHistogram_Average {
            get {
                return ResourceManager.GetString("PlayLogHistogram_Average", resourceCulture);
            }
        }
        
        /// <summary>
        /// 1時間 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogHistogram_Bucket_1Hour {
            get {
                return ResourceManager.GetString("PlayLogHistogram_Bucket_1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        /// 30分 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogHistogram_Bucket_30Minutes {
            get {
                return ResourceManager.GetString("PlayLogHistogram_Bucket_30Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        /// {0}時間～ のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogHistogram_BucketLabelFormat {
            get {
                return ResourceManager.GetString("PlayLogHistogram_BucketLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// {0}回 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogHistogram_CountTooltipFormat {
            get {
                return ResourceManager.GetString("PlayLogHistogram_CountTooltipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// プレイ時間の最大値 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogHistogram_Maximum {
            get {
                return ResourceManager.GetString("PlayLogHistogram_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        /// プレイ時間の中央値 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogHistogram_Median {
            get {
                return ResourceManager.GetString("PlayLogHistogram_Median", resourceCulture);
            }
        }
        
        /// <summary>
        /// No Data のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogHistogram_NoData {
            get {
                return ResourceManager.GetString("PlayLogHistogram_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        /// 間隔でまとめたプレイ時間の頻度 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogHistogram_Title {
            get {
                return ResourceManager.GetString("PlayLogHistogram_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// 初回プレイ のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogs_FirstPlayed {
            get {
                return ResourceManager.GetString("PlayLogs_FirstPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        /// 最終プレイ のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogs_LastPlayed {
            get {
                return ResourceManager.GetString("PlayLogs_LastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        /// 過去1年 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogs_LastYear {
            get {
                return ResourceManager.GetString("PlayLogs_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        /// のプレイ履歴 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogs_PlayHistorySuffix {
            get {
                return ResourceManager.GetString("PlayLogs_PlayHistorySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        /// {0}時間 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayLogs_TooltipHoursFormat {
            get {
                return ResourceManager.GetString("PlayLogs_TooltipHoursFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// {0}時間 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayTime_HoursFormat {
            get {
                return ResourceManager.GetString("PlayTime_HoursFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// {0}分 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayTime_MinutesFormat {
            get {
                return ResourceManager.GetString("PlayTime_MinutesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// {0}秒 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayTime_SecondsFormat {
            get {
                return ResourceManager.GetString("PlayTime_SecondsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルートを追加 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_Add {
            get {
                return ResourceManager.GetString("Root_Add", resourceCulture);
            }
        }
        
        /// <summary>
        /// 未割り当てのプレイ時間すべてをルートに割り当てる のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_AllocateAllUnallocatedPlayTime {
            get {
                return ResourceManager.GetString("Root_AllocateAllUnallocatedPlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルートに割り当てるプレイ時間 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_AssignedPlayTimeHeader {
            get {
                return ResourceManager.GetString("Root_AssignedPlayTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルート攻略日 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_ClearedAtHeader {
            get {
                return ResourceManager.GetString("Root_ClearedAtHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルート攻略済み のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_ClearedCheckBox {
            get {
                return ResourceManager.GetString("Root_ClearedCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        /// {0}に攻略 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_ClearedTooltipFormat {
            get {
                return ResourceManager.GetString("Root_ClearedTooltipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルートの色 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_ColorTooltip {
            get {
                return ResourceManager.GetString("Root_ColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルート編集 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_Edit {
            get {
                return ResourceManager.GetString("Root_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルートの編集 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_EditTitle {
            get {
                return ResourceManager.GetString("Root_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルート名 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_NameHeader {
            get {
                return ResourceManager.GetString("Root_NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// 新しいルート名 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_NewNameHeader {
            get {
                return ResourceManager.GetString("Root_NewNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルートに割り当てるプレイ時間は {0} 以下を指定してください。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_PlayTimeMaxErrorFormat {
            get {
                return ResourceManager.GetString("Root_PlayTimeMaxErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルートに割り当てるプレイ時間は1秒以上を指定してください。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_PlayTimeMinOneSecondError {
            get {
                return ResourceManager.GetString("Root_PlayTimeMinOneSecondError", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルートの追加 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_RegistrationTitle {
            get {
                return ResourceManager.GetString("Root_RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルート削除 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_Remove {
            get {
                return ResourceManager.GetString("Root_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルートの削除に失敗しました。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_RemoveFailed {
            get {
                return ResourceManager.GetString("Root_RemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルートの削除 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_RemoveTitle {
            get {
                return ResourceManager.GetString("Root_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// （未割り当てのルート） のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Root_UnallocatedLabel {
            get {
                return ResourceManager.GetString("Root_UnallocatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// 表示言語 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        /// 設定 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// サムネイル画像の取得に失敗しました。
        ///{0} のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Thumbnail_DownloadFailedFormat {
            get {
                return ResourceManager.GetString("Thumbnail_DownloadFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// ブランドを入力してください。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_BrandRequired {
            get {
                return ResourceManager.GetString("Validation_BrandRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// 攻略日を入力してください。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_ClearedAtRequired {
            get {
                return ResourceManager.GetString("Validation_ClearedAtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// 実行ファイルの場所を入力してください。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_ExecutableFilePathRequired {
            get {
                return ResourceManager.GetString("Validation_ExecutableFilePathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// 指定された場所にファイルが存在しません。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_FileNotFound {
            get {
                return ResourceManager.GetString("Validation_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// サムネイル画像の場所を入力してください。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_ImageUriRequired {
            get {
                return ResourceManager.GetString("Validation_ImageUriRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// プロパティ '{0}' が見つかりません。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_PropertyNotFoundFormat {
            get {
                return ResourceManager.GetString("Validation_PropertyNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// プレイ時間を入力してください。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_PlayTimeRequired {
            get {
                return ResourceManager.GetString("Validation_PlayTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// 発売日を入力してください。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_ReleaseDateRequired {
            get {
                return ResourceManager.GetString("Validation_ReleaseDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// ルート名を入力してください。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_RootNameRequired {
            get {
                return ResourceManager.GetString("Validation_RootNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// 不正な時間の形式です。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_TimeSpanFormat {
            get {
                return ResourceManager.GetString("Validation_TimeSpanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// タイトルを入力してください。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_TitleRequired {
            get {
                return ResourceManager.GetString("Validation_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// 有効な拡張子は {0} のいずれかです。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_ValidExtensionsFormat {
            get {
                return ResourceManager.GetString("Validation_ValidExtensionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// ウィンドウタイトルを入力してください。 のようなローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_WindowTitleRequired {
            get {
                return ResourceManager.GetString("Validation_WindowTitleRequired", resourceCulture);
            }
        }
    }
}
